{
    'name': 'RAMA EMS',
    'version': '12.0.1',
    'author': 'laxicon solution',
    'website': 'www.laxiconsolution.com',
    'catagory': 'school',
    'license': 'AGPL-3',
    'Summary': 'RAMA EMS',
    'description': 'This module is for school management',
    'depends': ['base', 'hr', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'security/school_security.xml',
        'data/sequence_code.xml',
        'views/school_student.xml',
        'views/school_admission.xml',
        'views/school_parent.xml',
        'views/academic_year.xml',
        'views/school_configuration.xml',
        'views/fees_configuration.xml',
        'views/school_admission.xml',
        'views/school_menu.xml',
    ],
    'installable': True,
    'application': True,
}